### ISSUE TITLE
Link from sourceforge?

### ISSUE THREAD

**Issue by beroe** [hohonuuli/vars#1]
Does this repo entirely replace the sourceforge one? Maybe put a link or explanation there, since SF comes up in The Google.

**Comment by hohonuuli** [comment]
Yes, this repo replaces the source forge one. I've added your suggestion to my todo list.

**Comment by beroe** [comment]
Great.  Thanks.

**Comment by hohonuuli** [comment]
The [sourceforge page](http://vars.sourceforge.net/) had been stripped off content accept for a link to the gitub repo.
