### ISSUE TITLE
Slow play doesn't work after pause

### ISSUE THREAD

**Issue by mkbassett** [hohonuuli/vars#5]
If I pause to record an annotation then click on the slow play button, nothing happens (even after waiting). If I hit rewind, then slow play again, it works. Rob and I were both having this issue on Friday and it started again this morning for me. We are both working on files. Kyra didn't have this issue with tapes.

**Comment by hohonuuli** [comment]
@mkbassett: Thanks for reporting this. Just a note that this is the issue tracker for the old VARS. For the new VARS/M3 annotation, would you please post the issues under <https://github.com/mbari-media-management/vars-annotation/issues>? Thanks!

**Comment by hohonuuli** [comment]
p.s. I've already moved this issue under vars-annotation.
