### ISSUE TITLE
VARS Query image download fail

### ISSUE THREAD

**Issue by lonnylundsten** [hohonuuli/vars#7]
After running a query with the VARS X Query tool, I selected download images but the process failed. I did get a directory structure dowloaded, but it contained no images. 

Here's an example path of the directory structure that was generated: /Users/lonny/Desktop/Acanthogorgia/Tiburon/images/0892/02_13_38_29.jpg, http:/search.mbari.org/ARCHIVE/frameGrabs/Tiburon/images/0892

**Comment by hohonuuli** [comment]
This has been fixed.
