### ISSUE TITLE
Fix performing-behavior type associations.

### ISSUE THREAD

**Issue by lonnylundsten** [hohonuuli/vars#8]
Assign to Lonny

**Comment by lonnylundsten** [comment]
I fixed this issue by running the following code for each change needed. Leaving this ticket open as there may be a few more global changes like this yet to be changed..


Change all concepts where association = 'performing | brooding | nil'
using the following code:
UPDATE associations 
SET link_name = 'brooding',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'nil'	
	AND to_concept = 'brooding'

Change all concepts where association = 'performing | behavior | brooding'
using the following code:
UPDATE associations 
SET link_name = 'brooding',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'brooding'	
	AND to_concept = 'behavior'


Change all concepts where association = 'performing | behavior | free-swimming'
using the following code:
UPDATE associations 
SET link_name = 'free-swimming',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'free-swimming'	
	AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | parachuting'
using the following code:
UPDATE associations 
SET link_name = 'parachuting',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'parachuting'	
	AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | swimming up'
using the following code:
UPDATE associations 
SET link_name = 'swimming-up',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'swimming up'	
	AND to_concept = 'behavior'


Change all concepts where association = 'performing | behavior | swimming'
using the following code:
UPDATE associations 
SET link_name = 'swimming',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'swimming'	
	AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | curling'
using the following code:
UPDATE associations 
SET link_name = 'curling',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'curling'	
	AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | damaged'
using the following code:
UPDATE associations 
SET link_name = 'damaged',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'damaged'	
	AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | drifting'
using the following code:
UPDATE associations 
SET link_name = 'drifting',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'drifting'	
	AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | escaping'
using the following code:
UPDATE associations 
SET link_name = 'escaping',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'escaping'	
	AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | hanging'
using the following code:
UPDATE associations 
SET link_name = 'hanging',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'hanging'	
	AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | hovering'
using the following code:
UPDATE associations 
SET link_name = 'hovering',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'hovering'	
	AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | inactive'
using the following code:
UPDATE associations 
SET link_name = 'inactive',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'inactive'	
	AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | inking'
using the following code:
UPDATE associations 
SET link_name = 'inking',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'inking'	
	AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | j-posing'
using the following code:
UPDATE associations 
SET link_name = 'j-posing',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'j-posing'	
	AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | pulsing'
using the following code:
UPDATE associations 
SET link_name = 'pulsing',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'pulsing'	
	AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | pursuing'
using the following code:
UPDATE associations 
SET link_name = 'pursuing',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'pursuing'	
	AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | rotating'
using the following code:
UPDATE associations 
SET link_name = 'rotating',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'rotating'	
	AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | somersaulting'
using the following code:
UPDATE associations 
SET link_name = 'somersaulting',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'somersaulting'	
	AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | walking'
using the following code:
UPDATE associations 
SET link_name = 'walking',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'walking'	
	AND to_concept = 'behavior'

Change all concepts where association = 'performing | defecating | nil'
using the following code:
UPDATE associations 
SET link_name = 'defecating',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'nil'	
	AND to_concept = 'defecating'

Change all concepts where association = 'performing | diving | nil'
using the following code:
UPDATE associations 
SET link_name = 'diving',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'nil'	
	AND to_concept = 'diving'

Change all concepts where association = 'performing | drifting | nil'
using the following code:
UPDATE associations 
SET link_name = 'drifting',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'nil'	
	AND to_concept = 'drifting'

Change all concepts where association = 'performing | parachuting | nil'
using the following code:
UPDATE associations 
SET link_name = 'parachuting',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'nil'	
	AND to_concept = 'parachuting'

Change all concepts where association = 'performing | somersaulting | nil'
using the following code:
UPDATE associations 
SET link_name = 'somersaulting',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'nil'	
	AND to_concept = 'somersaulting'

Change all concepts where association = 'performing | swimming | nil'
using the following code:
UPDATE associations 
SET link_name = 'swimming',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'nil'	
	AND to_concept = 'swimming'

Change all concepts where association = 'performing | parachuting | parachuting'
using the following code:
UPDATE associations 
SET link_name = 'parachuting',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'parachuting'	
	AND to_concept = 'parachuting'

Change all concepts where association = 'performing | fishing | nil'
using the following code:
UPDATE associations 
SET link_name = 'fishing',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'nil'	
	AND to_concept = 'fishing'

Change all concepts where association = 'performing | j-posing | nil'
using the following code:
UPDATE associations 
SET link_name = 'j-posing',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'nil'	
	AND to_concept = 'j-posing'

Change all concepts where association = 'performing | inactive | nil'
using the following code:
UPDATE associations 
SET link_name = 'inactive',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'nil'	
	AND to_concept = 'inactive'

Change all concepts where association = 'performing | nil | curling'
using the following code:
UPDATE associations 
SET link_name = 'curling',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'curling'	
	AND to_concept = 'nil'

Change all concepts where association = 'performing | nil | rotating'
using the following code:
UPDATE associations 
SET link_name = 'rotating',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'rotating'	
	AND to_concept = 'nil'

Change all concepts where association = 'performing | nil | digging'
using the following code:
UPDATE associations 
SET link_name = 'digging',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'digging'	
	AND to_concept = 'nil'

Change all concepts where association = 'performing | nil | fail'
using the following code:
UPDATE associations 
SET link_name = 'fail',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'fail'	
	AND to_concept = 'nil'

**Comment by lonnylundsten** [comment]
Change all concepts where association = 'performing | brooding | eggmass'
using the following code:
UPDATE associations 
SET link_name = 'brooding',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'eggmass'	
	AND to_concept = 'brooding'

Change all concepts where association = 'performing | brooding | eggs'
using the following code:
UPDATE associations 
SET link_name = 'brooding',
link_value = 'nil',
to_concept = 'nil' 
WHERE
	link_name = 'performing'	
	AND link_value = 'eggs'	
	AND to_concept = 'brooding'

Change all concepts where association = 'life-stage | self | brooding young'
using the following code:
UPDATE associations 
SET link_name = 'comment'
WHERE
	link_name = 'life-stage'	
	AND link_value = 'brooding young'	
	AND to_concept = 'self'

**Comment by lindakuhnz** [comment]
Additional:

UPDATE associations
SET link_name = 'photophores flashing',
link_value = 'nil',
to_concept = 'nil'
WHERE
link_name = 'performing'
AND link_value = 'nil'
AND to_concept = 'photophores flashing'

UPDATE associations
SET link_name = 'landing',
link_value = 'nil',
to_concept = 'nil'
WHERE
link_name = 'performing'
AND link_value = 'nil'
AND to_concept = 'landing on benthos'

UPDATE associations
SET link_name = 'sinking',
link_value = 'nil',
to_concept = 'nil'
WHERE
link_name = 'performing'
AND link_value = 'nil'
AND to_concept = 'sinking'

UPDATE associations
SET link_name = 'photophores flashing',
link_value = 'nil',
to_concept = 'nil'
WHERE
link_name = 'performing'
AND link_value = 'nil'
AND to_concept = 'photophores blinking'

**Comment by lonnylundsten** [comment]
Additional:

Change all concepts where association = 'performing | behavior | landing on benthos'
using the following code:
UPDATE associations
SET link_name = 'landing',
link_value = 'nil',
to_concept = 'nil'
WHERE
link_name = 'performing'
AND link_value = 'landing on benthos'
AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | wriggling'
using the following code:
UPDATE associations
SET link_name = 'wriggling',
link_value = 'nil',
to_concept = 'nil'
WHERE
link_name = 'performing'
AND link_value = 'wriggling'
AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | sinking'
using the following code:
UPDATE associations
SET link_name = 'sinking',
link_value = 'nil',
to_concept = 'nil'
WHERE
link_name = 'performing'
AND link_value = 'sinking'
AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | photophores blinking'
using the following code:
UPDATE associations
SET link_name = 'photophores flashing',
link_value = 'nil',
to_concept = 'nil'
WHERE
link_name = 'performing'
AND link_value = 'photophores blinking'
AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | photophores flashing'
using the following code:
UPDATE associations
SET link_name = 'photophores flashing',
link_value = 'nil',
to_concept = 'nil'
WHERE
link_name = 'performing'
AND link_value = 'photophores flashing'
AND to_concept = 'behavior'

Change all concepts where association = 'performing | behavior | photopores flashing'
using the following code:
UPDATE associations
SET link_name = 'photophores flashing',
link_value = 'nil',
to_concept = 'nil'
WHERE
link_name = 'performing'
AND link_value = 'photopores flashing'
AND to_concept = 'behavior'

**Comment by lonnylundsten** [comment]
closing issue
